### ISSUE TITLE
Test data file path

### ISSUE THREAD

**Issue by FlukeAndFeather** [sjeknic/finalproject#4]
As a rule of thumb, if you're using `setwd()` then there's probably a better strategy. Let's chat about your test file.

https://github.com/sjeknic/finalproject/blob/ddac40b30bfaa6bc107b612442dc48f3cc81f233/tests/testthat/test-plots.R#L5-L7

**Comment by FlukeAndFeather** [comment]
e.g. `here::here("analysis/data/raw_data/supp_table4.csv")`

**Comment by ggsun** [comment]
Thank you! This has been resolved with 8a6b992.
